/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;
import Data.DocGhiExel;
import Data.ExportPDF;
import Data.ThuThuData;
import Object.ThuThu;
import com.itextpdf.text.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
/**
 *
 * @author Admin
 */
public class JQuanLy extends javax.swing.JFrame {
    public static PreparedStatement ps = null;
     public static int click =0;
    ThuThuData thuthu=new ThuThuData();
String sql="select*from BangNhanVien order by MaNhanVien asc";
DefaultTableModel tbn=new DefaultTableModel();
public static String cot1, bang1;
    /**
     * Creates new form JQuanLy
     */
    public JQuanLy() {
        initComponents();
        UpdateTable.LoadData(sql, tbNV);
        UpdateTable.LoadData(sql, tbTKNV);
        ProcessCrt(false);
    }
public void ProcessCrt(boolean b){
    this.btThemNV.setEnabled(b);
    this.btSuaNV.setEnabled(b);
    this.btXoaNV.setEnabled(b);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNV = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMNV = new javax.swing.JTextField();
        txtTNV = new javax.swing.JTextField();
        txtNS = new javax.swing.JTextField();
        txtGT = new javax.swing.JTextField();
        txtEM = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDC = new javax.swing.JTextField();
        btThemNV = new javax.swing.JButton();
        btSuaNV = new javax.swing.JButton();
        btXoaNV = new javax.swing.JButton();
        btNewNV = new javax.swing.JButton();
        btThemFileNV = new javax.swing.JButton();
        btXuatFileNV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTKNV = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTKMNV = new javax.swing.JTextField();
        txtTKTNV = new javax.swing.JTextField();
        txtTKNSNV = new javax.swing.JTextField();
        txtTKGTNV = new javax.swing.JTextField();
        txtTKEMNV = new javax.swing.JTextField();
        txtTKSDTNV = new javax.swing.JTextField();
        txtTKDCNV = new javax.swing.JTextField();
        btTKNV = new javax.swing.JButton();
        btNewTK = new javax.swing.JButton();
        btInTK = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbThongKeNV = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        btThongKeTNV = new javax.swing.JButton();
        btThongkeGT = new javax.swing.JButton();
        btThongkeNS = new javax.swing.JButton();
        btThongKeDC = new javax.swing.JButton();
        btInThongKe = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý thư viện");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\main thủ thư.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Giới thiệu", jPanel1);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        tbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNV);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Info.png")); // NOI18N
        jLabel4.setText("Cập nhật thông tin nhân viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tên nhân viên:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Giới tính:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Số điện thoại:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Địa chỉ:");

        btThemNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThemNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\nhập lại (5).png")); // NOI18N
        btThemNV.setText("Thêm");
        btThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemNVActionPerformed(evt);
            }
        });

        btSuaNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSuaNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\sửa.png")); // NOI18N
        btSuaNV.setText("Sửa");
        btSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaNVActionPerformed(evt);
            }
        });

        btXoaNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoaNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\xóa.png")); // NOI18N
        btXoaNV.setText("Xóa");
        btXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaNVActionPerformed(evt);
            }
        });

        btNewNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\nhập lại (1).png")); // NOI18N
        btNewNV.setText("Nhập mới");
        btNewNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewNVActionPerformed(evt);
            }
        });

        btThemFileNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThemFileNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\thêm file.png")); // NOI18N
        btThemFileNV.setText("Thêm File");
        btThemFileNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemFileNVActionPerformed(evt);
            }
        });

        btXuatFileNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXuatFileNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\xuất file.png")); // NOI18N
        btXuatFileNV.setText("Xuất File");
        btXuatFileNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXuatFileNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEM, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTNV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMNV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDC, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNewNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btThemFileNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btXuatFileNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThemNV)
                            .addComponent(btSuaNV)
                            .addComponent(btXoaNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNewNV)
                            .addComponent(btXuatFileNV)
                            .addComponent(btThemFileNV))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thêm, sửa,xóa", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        tbTKNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbTKNV);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Info.png")); // NOI18N
        jLabel12.setText("Tìm kiếm thông tin nhân viên");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mã nhân viên:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tên nhân viên:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Ngày sinh:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Giới tính:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Email:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Số điện thoại:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Địa chỉ:");

        btTKNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTKNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\timkiem2.png")); // NOI18N
        btTKNV.setText("Tìm kiếm");
        btTKNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKNVActionPerformed(evt);
            }
        });

        btNewTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewTK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\nhập lại (1).png")); // NOI18N
        btNewTK.setText("Nhập lại");
        btNewTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTKActionPerformed(evt);
            }
        });

        btInTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btInTK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\xuất file.png")); // NOI18N
        btInTK.setText("In");
        btInTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTKMNV, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                            .addComponent(txtTKTNV)
                                            .addComponent(txtTKNSNV)
                                            .addComponent(txtTKGTNV)
                                            .addComponent(txtTKEMNV)
                                            .addComponent(txtTKSDTNV)
                                            .addComponent(txtTKDCNV)))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btTKNV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btNewTK)
                                .addGap(22, 22, 22))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btInTK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtTKMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTKTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTKNSNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtTKGTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtTKEMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtTKSDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtTKDCNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTKNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btNewTK))
                        .addGap(18, 18, 18)
                        .addComponent(btInTK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tìm kiếm", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        tbThongKeNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbThongKeNV);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Thống kê nhân viên");

        btThongKeTNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThongKeTNV.setText("Theo tên nhân viên");
        btThongKeTNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeTNVActionPerformed(evt);
            }
        });

        btThongkeGT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThongkeGT.setText("Theo giới tính");
        btThongkeGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongkeGTActionPerformed(evt);
            }
        });

        btThongkeNS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThongkeNS.setText("Theo ngày sinh");
        btThongkeNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongkeNSActionPerformed(evt);
            }
        });

        btThongKeDC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThongKeDC.setText("Địa chỉ");
        btThongKeDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeDCActionPerformed(evt);
            }
        });

        btInThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInThongKe.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\xuất file.png")); // NOI18N
        btInThongKe.setText("In");
        btInThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInThongKeActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\thống kê.png")); // NOI18N
        jLabel21.setText("Thống kê nhân viên theo:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btThongkeGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThongkeNS, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(btThongKeDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addComponent(btInThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btThongKeTNV)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btThongKeTNV)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btThongkeNS))
                        .addGap(19, 19, 19)
                        .addComponent(btThongkeGT)
                        .addGap(29, 29, 29)
                        .addComponent(btThongKeDC))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel20)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thống kê", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Nhân viên", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thực hiện bởi: Nguyễn Thị Hải Yến-20167045");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\p.png")); // NOI18N
        jLabel3.setText("Xin chào quản lý!");

        btDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Exit.png")); // NOI18N
        btDangXuat.setText("Đăng xuất");
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(135, 135, 135)
                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNVMouseClicked
        // TODO add your handling code here:
        ProcessCrt(true);
        this.btThemNV.setEnabled(false);
        try{
            int row = this.tbNV.getSelectedRow();
            String IDrow = (this.tbNV.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM BangNhanVien where MaNhanVien='"+IDrow+"'";
            ResultSet rs = UpdateTable.ShowTextField(sql1);
            if(rs.next()) {
                this.txtMNV.setText(rs.getString("MaNhanVien"));
                this.txtTNV.setText(rs.getString("TenNhanVien"));
                this.txtNS.setText(rs.getString("Ngaysinh"));
                this.txtGT.setText(rs.getString("Gioitinh"));
                this.txtEM.setText((rs.getString("Email")));
                this.txtSDT.setText(rs.getString("Sodienthoai"));
                this.txtDC.setText(rs.getString("Diachi"));
              
            }
        }catch(Exception e) {

        }
    }//GEN-LAST:event_tbNVMouseClicked

    private void btNewNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewNVActionPerformed
        // TODO add your handling code here:
        this.btThemNV.setEnabled(true);
        this.btSuaNV.setEnabled(false);
        this.btXoaNV.setEnabled(false);
        this.txtMNV.setText(null);
        this.txtTNV.setText(null);
        this.txtNS.setText(null);
        this.txtGT.setText(null);
        this.txtEM.setText(null);
        this.txtSDT.setText(null);
        this.txtDC.setText(null);
    }//GEN-LAST:event_btNewNVActionPerformed

    private void btThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemNVActionPerformed
        // TODO add your handling code here:
         try{
            if (this.txtMNV.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã nhân viên không thể bỏ trống", "thông báo", 2);
            //else if(this.txtMNV.getText().length()>50) JOptionPane.showMessageDialog(null, "Mã nhân viên không được lớn hơn 50 ký tự", "thông báo", 2);
            else {
                ThuThu s = new ThuThu(this.txtMNV.getText(),this.txtTNV.getText(),
                        Date.valueOf(this.txtNS.getText()),this.txtGT.getText(),this.txtEM.getText(),this.txtSDT.getText(),this.txtDC.getText());
                ThuThuData.InsertThuThu(s);
                String sql2="Select*from BangNhanVien";
                UpdateTable.LoadData(sql2, tbNV);
                //  this.btTK.doClick();
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
        }
    }//GEN-LAST:event_btThemNVActionPerformed

    private void btSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaNVActionPerformed
        // TODO add your handling code here:
          if (this.txtMNV.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã nhân viên không thể bỏ trống", "thông báo", 2);
        //else if(this.txtMNV.getText().length()>50) JOptionPane.showMessageDialog(null, "Mã nhân viên không được lớn hơn 50 ký tự", "thông báo", 2);
        else {
            ThuThu s = new ThuThu(this.txtMNV.getText(),this.txtTNV.getText(),
                        Date.valueOf(this.txtNS.getText()),this.txtGT.getText(),this.txtEM.getText(),this.txtSDT.getText(),this.txtDC.getText());
            if(thuthu.UpdateThuThu(s)) {
                JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
                String sql3="select*from BangNhanVien";
                UpdateTable.LoadData(sql3, tbNV);
            }
            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            //this.btTK.doClick();
        }
    }//GEN-LAST:event_btSuaNVActionPerformed

    private void btXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaNVActionPerformed
        // TODO add your handling code here:
        if (this.txtMNV.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã nhân viên không thể bỏ trống", "thông báo", 2);
        //else if(this.txtMS.getText().length()>50) JOptionPane.showMessageDialog(null, "Mã nhân viên không được lớn hơn 50 ký tự", "thông báo", 2);
        else {
            if(thuthu.DeleteThuThu(this.txtMNV.getText())) {
                if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?","Xác nhận",
                    JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
                JOptionPane.showMessageDialog(this, "Bạn đã xóa thành công!");
                //JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
            }
            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            UpdateTable.LoadData(sql, tbNV);
            //this.btTK.doClick();
        }
        }
    }//GEN-LAST:event_btXoaNVActionPerformed

    private void btXuatFileNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXuatFileNVActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Save file");
        int choose = chooser.showSaveDialog(null);
        File file = chooser.getSelectedFile();
         DefaultTableModel model1 = (DefaultTableModel) tbNV.getModel();
         if (choose == JFileChooser.APPROVE_OPTION) {
                        DocGhiExel rp = new DocGhiExel();
                        rp.getExcel("DANH SÁCH SÁCH HIỆN TẠI", model1, file);
                        JOptionPane.showMessageDialog(getParent(), " Đã lưu !!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }
    }//GEN-LAST:event_btXuatFileNVActionPerformed

    private void btTKNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKNVActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM BangNhanVien WHERE ";
        int kiemtra = 0;
        String manhanvien = this.txtTKMNV.getText();
        String tennhanvien = this.txtTKTNV.getText();
        String ngaysinh = this.txtTKNSNV.getText();
        String gioitinh = this.txtTKGTNV.getText();
        String email = this.txtTKEMNV.getText();
        String sdt = this.txtTKSDTNV.getText();
        String diachi = this.txtTKDCNV.getText();
        
        if (manhanvien.length() == 0 && tennhanvien.length() == 0 && ngaysinh.length() == 0
            && gioitinh.length() == 0 && email.length() == 0 && sdt.length() == 0 && diachi.length()==0)

        JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin tìm kiếm!", "Thông báo", 1);
        else
        {
            if (manhanvien.length() > 0)
            {
                sql = sql + "MaNhanVien LIKE '%"+manhanvien+"%'";
                kiemtra = 1;
            }
            if (tennhanvien.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "TenNhanVien LIKE N'%"+tennhanvien+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND TenNhanVien LIKE N'%"+tennhanvien+"%'";
            }
            if (ngaysinh.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Ngaysinh LIKE '%"+ngaysinh+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Ngaysinh LIKE '%"+ngaysinh+"%'";
            }
            if (gioitinh.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Gioitinh LIKE N'%"+gioitinh+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Gioitinh LIKE N'%"+gioitinh+"%'";
            }

            if (email.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Email LIKE N'%"+email+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Email LIKE N'%"+email+"%'";
            }
            if (sdt.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Sodienthoai LIKE '%"+sdt+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Sodienthoai LIKE '%"+sdt+"%'";
            }
            if (diachi.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Diachi LIKE N'%"+diachi+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Diachi LIKE N'%"+diachi+"%'";
            }
            

            UpdateTable.LoadData(sql, tbTKNV);
        }
    }//GEN-LAST:event_btTKNVActionPerformed

    private void btNewTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTKActionPerformed
        // TODO add your handling code here:
        this.txtTKMNV.setText(null);
        this.txtTKTNV.setText(null);
        this.txtTKNSNV.setText(null);
        this.txtTKGTNV.setText(null);
        this.txtTKEMNV.setText(null);
        this.txtTKSDTNV.setText(null);
        this.txtTKDCNV.setText(null);
    }//GEN-LAST:event_btNewTKActionPerformed

    private void btInTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInTKActionPerformed
        // TODO add your handling code here:
          try {
            ExportPDF.XuatTimKiem(tbTKNV, "Nhân viên", "C:\\Users\\Admin\\Documents\\đồ án 1\\Xuất file biểu mẫu/");
        } catch (Exception e) {
        }    
    }//GEN-LAST:event_btInTKActionPerformed

    private void btThongKeTNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeTNVActionPerformed
        // TODO add your handling code here:
         click=1;
        String tktnv="Select TenNhanVien as 'Tên nhân viên', count(TenNhanVien) as 'Số lượng' from BangNhanVien group by TenNhanVien";
        UpdateTable.LoadData(tktnv, tbThongKeNV);
    }//GEN-LAST:event_btThongKeTNVActionPerformed

    private void btThongkeNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongkeNSActionPerformed
        // TODO add your handling code here:
         click=2;
        String tktnv="Select Ngaysinh as 'Ngày sinh', count(Ngaysinh) as 'Số lượng' from BangNhanVien group by Ngaysinh";
        UpdateTable.LoadData(tktnv, tbThongKeNV);
    }//GEN-LAST:event_btThongkeNSActionPerformed

    private void btThongkeGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongkeGTActionPerformed
        // TODO add your handling code here:
         click=3;
        String tktnv="Select Gioitinh as 'Giới tính', count(Gioitinh) as 'Số lượng' from BangNhanVien group by Gioitinh";
        UpdateTable.LoadData(tktnv, tbThongKeNV);
    }//GEN-LAST:event_btThongkeGTActionPerformed

    private void btThongKeDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeDCActionPerformed
        // TODO add your handling code here:
         click=4;
        String tktnv="Select Diachi as 'Địa chỉ', count(Diachi) as 'Số lượng' from BangNhanVien group by Diachi";
        UpdateTable.LoadData(tktnv, tbThongKeNV);
    }//GEN-LAST:event_btThongKeDCActionPerformed

    private void btInThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInThongKeActionPerformed
        // TODO add your handling code here:
         switch (click) {
            case  1:
            try {
                ExportPDF.XuatTK( tbThongKeNV, "bảng nhân viên", "Tên nhân viên", "Tên nhân viên", "Số lượng","C:\\Users\\Admin\\Documents\\đồ án 1\\Xuất file biểu mẫu/");
            } catch (Exception ex) {
            }   break;
            case 2:
            try {
                ExportPDF.XuatTK(tbThongKeNV, "bảng nhân viên", "Ngày sinh", "Ngày sinh", "Số lượng","C:\\Users\\Admin\\Documents\\đồ án 1\\Xuất file biểu mẫu/");
            } catch (Exception ex) {
            }   break;
            case 3:
            try {
                ExportPDF.XuatTK(tbThongKeNV, "bảng nhân viên", "Giới tính", "Giới tính", "Số lượng","C:\\Users\\Admin\\Documents\\đồ án 1\\Xuất file biểu mẫu/");
            } catch (Exception ex) {
            }   break;

            case 4:
            try {
                ExportPDF.XuatTK(tbThongKeNV, "bảng nhân viên", "Địa chỉ", "Địa chỉ", "Số lượng","C:\\Users\\Admin\\Documents\\đồ án 1\\Xuất file biểu mẫu/");
            } catch (Exception ex) {
            }   break;
         }
    }//GEN-LAST:event_btInThongKeActionPerformed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất không?","Xác nhận",
                  JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
              Login t= new Login();
              t.setVisible(true);
              dispose();
              JOptionPane.showMessageDialog(this, "Bạn đã đăng xuất thành công!");
         }
    }//GEN-LAST:event_btDangXuatActionPerformed

    private void btThemFileNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemFileNVActionPerformed
        // TODO add your handling code here:
          String MaNV="";
        String TenNv="";
        String NS="";
        String GT="";
        String EM="";
        String SDT="";
        String DC="";
        
        try {
            File f=new File("C:\\Users\\Admin\\Documents\\đồ án 1\\Thêm file\\Thêm nhân viên.xls");
            Workbook wb=Workbook.getWorkbook(f);
            Sheet s=wb.getSheet(0);
            int row=s.getRows();
            int col=s.getColumns();
            for(int i = 0;i<row;i++){
                Cell c= s. getCell(0,i);
                MaNV=c.getContents();
                c= s. getCell(1,i);
                TenNv=c.getContents();
                c= s. getCell(2,i);
                NS=c.getContents().toString();
                c= s. getCell(3,i);
                GT=c.getContents();
                c= s. getCell(4,i);
                EM=c.getContents();
                c= s. getCell(5,i);
                SDT=c.getContents();
                c= s. getCell(6,i);
                DC=c.getContents();
               
        String query="insert into BangNhanVien values('"+MaNV+"','"+TenNv+"','"+NS+"','"+GT+"','"+EM+"','"+SDT+"','"+DC+"')";
        if (txtMNV.getText().equals(s)) JOptionPane.showMessageDialog(this, "Mã nhân viên đã bị trùng");
        try{
            Data.Connect a=new Data.Connect();
            Connection conn=a.getConnect();
            Statement st=conn.createStatement();
            if(st.executeUpdate(query)==1){
                //JOptionPane.showMessageDialog(this, "Thêm File thành công!");
                 
               tbn.setRowCount(0);
                UpdateTable.LoadData(sql, tbNV);
            }
             //JOptionPane.showMessageDialog(this, "Thêm File thành công!");
            
        }catch(Exception e){
            System.out.println(e.toString());
        }
                
            }
        } catch (IOException ex) {
           Logger.getLogger(JQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(JQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
   JOptionPane.showMessageDialog(this, "Thêm File thành công!");
             


    }//GEN-LAST:event_btThemFileNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btInTK;
    private javax.swing.JButton btInThongKe;
    private javax.swing.JButton btNewNV;
    private javax.swing.JButton btNewTK;
    private javax.swing.JButton btSuaNV;
    private javax.swing.JButton btTKNV;
    private javax.swing.JButton btThemFileNV;
    private javax.swing.JButton btThemNV;
    private javax.swing.JButton btThongKeDC;
    private javax.swing.JButton btThongKeTNV;
    private javax.swing.JButton btThongkeGT;
    private javax.swing.JButton btThongkeNS;
    private javax.swing.JButton btXoaNV;
    private javax.swing.JButton btXuatFileNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbNV;
    private javax.swing.JTable tbTKNV;
    private javax.swing.JTable tbThongKeNV;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtEM;
    private javax.swing.JTextField txtGT;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JTextField txtNS;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTKDCNV;
    private javax.swing.JTextField txtTKEMNV;
    private javax.swing.JTextField txtTKGTNV;
    private javax.swing.JTextField txtTKMNV;
    private javax.swing.JTextField txtTKNSNV;
    private javax.swing.JTextField txtTKSDTNV;
    private javax.swing.JTextField txtTKTNV;
    private javax.swing.JTextField txtTNV;
    // End of variables declaration//GEN-END:variables
}
