/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;
import Data.DocGiaData;
import Object.DocGia;
import Data.SachData;
import Object.Sach;
import Data.MuonTraData;
import Object.MuonTra;
import Data.ThuThuData;
import Object.ThuThu;

import javax.swing.JOptionPane;

/**
 *
 * @author Hải Yến
 */
public class MainDocGia extends javax.swing.JFrame {
    
String sql="select *from BangSach order by MaSach asc";
String sql1="select *from BangNhanVien order by MaNhanVien asc";
String sql2="select *from BangMuonTra order by MaMuonTra asc";

    
    public MainDocGia() {
        initComponents();
        UpdateTable.LoadData(sql, tbTKS);
        UpdateTable.LoadData(sql1, tbTKNV);
        UpdateTable.LoadData(sql2, tbTKMT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTKS = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btTKS = new javax.swing.JButton();
        btNewTKS = new javax.swing.JButton();
        txtMS = new javax.swing.JTextField();
        txtTS = new javax.swing.JTextField();
        txtTG = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        txtTL = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        txtNB = new javax.swing.JTextField();
        txtDG = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTKNV = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btTKNV = new javax.swing.JButton();
        btNewTKNV = new javax.swing.JButton();
        txtTKMNV = new javax.swing.JTextField();
        txtTKTNV = new javax.swing.JTextField();
        txtTKNSNV = new javax.swing.JTextField();
        txtTKGTNV = new javax.swing.JTextField();
        txtTKEMNV = new javax.swing.JTextField();
        txtTKSDTNV = new javax.swing.JTextField();
        txtTKDCNV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTKMT = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTKMMT = new javax.swing.JTextField();
        btTKMDG = new javax.swing.JTextField();
        txtTKMaNV = new javax.swing.JTextField();
        txtTKNM = new javax.swing.JTextField();
        txtTKNHT = new javax.swing.JTextField();
        txtTKTC = new javax.swing.JTextField();
        btTKMT = new javax.swing.JButton();
        btnewMT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý thư viện");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\main thủ thư.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1236, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Giới thiệu", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Info.png")); // NOI18N
        jLabel4.setText("Tìm kiếm thông tin sách");

        tbTKS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTKS);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã sách:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tên sách:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tác giả:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nhà xuất bản:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Thể loại:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Số lượng:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Năm xuất bản:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Đơn giá:");

        btTKS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTKS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\timkiem2.png")); // NOI18N
        btTKS.setText("Tìm kiếm");
        btTKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKSActionPerformed(evt);
            }
        });

        btNewTKS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewTKS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\nhập lại (1).png")); // NOI18N
        btNewTKS.setText("Nhập lại");
        btNewTKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTKSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMS)
                                .addComponent(txtTS)
                                .addComponent(txtTG)
                                .addComponent(txtNXB)
                                .addComponent(txtTL)
                                .addComponent(txtSL)
                                .addComponent(txtNB)
                                .addComponent(txtDG, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btTKS)
                                .addGap(31, 31, 31)
                                .addComponent(btNewTKS)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtNB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNewTKS)
                            .addComponent(btTKS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sách", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Info.png")); // NOI18N
        jLabel13.setText("Tìm kiếm thông tin nhân viên");

        tbTKNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbTKNV);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Mã nhân viên:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tên nhân viên:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Ngày sinh:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Giới tính:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Email:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Số điện thoại:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Địa chỉ:");

        btTKNV.setBackground(new java.awt.Color(255, 255, 255));
        btTKNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTKNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\timkiem2.png")); // NOI18N
        btTKNV.setText("Tìm kiếm");
        btTKNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKNVActionPerformed(evt);
            }
        });

        btNewTKNV.setBackground(new java.awt.Color(255, 255, 255));
        btNewTKNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewTKNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\nhập lại (1).png")); // NOI18N
        btNewTKNV.setText("Nhập lại");
        btNewTKNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTKNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTKMNV)
                                    .addComponent(txtTKTNV)
                                    .addComponent(txtTKNSNV)
                                    .addComponent(txtTKGTNV)
                                    .addComponent(txtTKEMNV)
                                    .addComponent(txtTKSDTNV)
                                    .addComponent(txtTKDCNV, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(btTKNV)
                                .addGap(18, 18, 18)
                                .addComponent(btNewTKNV)
                                .addGap(101, 101, 101)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTKMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTKTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtTKNSNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtTKGTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtTKEMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtTKSDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtTKDCNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTKNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btNewTKNV)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhân viên", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Info.png")); // NOI18N
        jLabel21.setText("Tìm kiếm thông tin mượn trả");

        tbTKMT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbTKMT);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Mã mượn trả:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Mã độc giả:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Mã nhân viên:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Ngày mượn:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Ngày hẹn trả:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Tiền cọc:");

        txtTKTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKTCActionPerformed(evt);
            }
        });

        btTKMT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTKMT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\timkiem2.png")); // NOI18N
        btTKMT.setText("Tìm kiếm");
        btTKMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKMTActionPerformed(evt);
            }
        });

        btnewMT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnewMT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\nhập lại (1).png")); // NOI18N
        btnewMT.setText("Nhập lại");
        btnewMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewMTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTKMMT, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addComponent(btTKMDG)
                                .addComponent(txtTKMaNV)
                                .addComponent(txtTKNM)
                                .addComponent(txtTKNHT)
                                .addComponent(txtTKTC))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btTKMT)
                                .addGap(32, 32, 32)
                                .addComponent(btnewMT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtTKMMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(btTKMDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtTKMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtTKNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtTKNHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtTKTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTKMT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnewMT)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mượn Trả", jPanel4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thực hiện bởi: Nguyễn Thị Hải Yến-20167045");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\đọc giả11.png")); // NOI18N
        jLabel2.setText("Xin chào độc giả!");

        btDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ảnh đồ án\\Exit.png")); // NOI18N
        btDangXuat.setText("Đăng xuất");
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(67, 67, 67)
                .addComponent(btDangXuat)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất không?","Xác nhận",
                  JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
              Login t= new Login();
              t.setVisible(true);
              dispose();
              JOptionPane.showMessageDialog(this, "Bạn đã đăng xuất thành công!");
         }
    }//GEN-LAST:event_btDangXuatActionPerformed

    private void btNewTKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTKSActionPerformed
        // TODO add your handling code here:
        this.txtMS.setText(null);
        this.txtTS.setText(null);
        this.txtTG.setText(null);
        this.txtNXB.setText(null);
        this.txtTL.setText(null);
        this.txtSL.setText(null);
        this.txtNB.setText(null);
        this.txtDG.setText(null);
    }//GEN-LAST:event_btNewTKSActionPerformed

    private void btTKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKSActionPerformed
        // TODO add your handling code here:
         String sql = "SELECT * FROM BangSach WHERE ";
        int kiemtra = 0;
        String ms = this.txtMS.getText();
        String ts = this.txtTS.getText();
        String tg = this.txtTG.getText();
        String nxb = this.txtNXB.getText();
        String tl = this.txtTL.getText();
        String sl = this.txtSL.getText();
        String nb = this.txtNB.getText();
        String dg = this.txtDG.getText();
        
        if (ms.length() == 0 && ts.length() == 0 && tg.length() == 0
            && nxb.length() == 0 && tl.length() == 0 && sl.length() == 0 && nb.length()==0&& dg.length()==0)

        JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin tìm kiếm!", "Thông báo", 1);
        else
        {
            if (ms.length() > 0)
            {
                sql = sql + "MaSach LIKE '%"+ms+"%'";
                kiemtra = 1;
            }
            if (ts.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "TenSach LIKE N'%"+ts+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND TenSach LIKE N'%"+ts+"%'";
            }
            if (tg.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Tacgia LIKE N'%"+tg+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Tacgia LIKE N'%"+tg+"%'";
            }
            if (nxb.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Nhaxuatban LIKE N'%"+nxb+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Nhaxuatban LIKE N'%"+nxb+"%'";
            }

            if (tl.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "TheLoai LIKE N'%"+tl+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND TheLoai LIKE N'%"+tl+"%'";
            }
            if (sl.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Soluong LIKE '%"+sl+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Soluong LIKE '%"+sl+"%'";
            }
            if (nb.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "NamXB LIKE '%"+nb+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND NamXB LIKE '%"+nb+"%'";
            }
            if (dg.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "DonGia LIKE '%"+dg+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND DonGia LIKE '%"+dg+"%'";
            }

            UpdateTable.LoadData(sql, tbTKS);
        }
    }//GEN-LAST:event_btTKSActionPerformed

    private void btNewTKNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTKNVActionPerformed
        // TODO add your handling code here:
         this.txtTKMNV.setText(null);
        this.txtTKTNV.setText(null);
        this.txtTKNSNV.setText(null);
        this.txtTKGTNV.setText(null);
        this.txtTKEMNV.setText(null);
        this.txtTKSDTNV.setText(null);
        this.txtTKDCNV.setText(null);
    }//GEN-LAST:event_btNewTKNVActionPerformed

    private void btTKNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKNVActionPerformed
        // TODO add your handling code here:
         String sql = "SELECT * FROM BangNhanVien WHERE ";
        int kiemtra = 0;
        String manhanvien = this.txtTKMNV.getText();
        String tennhanvien = this.txtTKTNV.getText();
        String ngaysinh = this.txtTKNSNV.getText();
        String gioitinh = this.txtTKGTNV.getText();
        String email = this.txtTKEMNV.getText();
        String sdt = this.txtTKSDTNV.getText();
        String diachi = this.txtTKDCNV.getText();
        
        if (manhanvien.length() == 0 && tennhanvien.length() == 0 && ngaysinh.length() == 0
            && gioitinh.length() == 0 && email.length() == 0 && sdt.length() == 0 && diachi.length()==0)

        JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin tìm kiếm!", "Thông báo", 1);
        else
        {
            if (manhanvien.length() > 0)
            {
                sql = sql + "MaNhanVien LIKE '%"+manhanvien+"%'";
                kiemtra = 1;
            }
            if (tennhanvien.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "TenNhanVien LIKE N'%"+tennhanvien+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND TenNhanVien LIKE N'%"+tennhanvien+"%'";
            }
            if (ngaysinh.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Ngaysinh LIKE '%"+ngaysinh+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Ngaysinh LIKE '%"+ngaysinh+"%'";
            }
            if (gioitinh.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Gioitinh LIKE N'%"+gioitinh+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Gioitinh LIKE N'%"+gioitinh+"%'";
            }

            if (email.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Email LIKE N'%"+email+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Email LIKE N'%"+email+"%'";
            }
            if (sdt.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Sodienthoai LIKE '%"+sdt+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Sodienthoai LIKE '%"+sdt+"%'";
            }
            if (diachi.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "Diachi LIKE N'%"+diachi+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND Diachi LIKE N'%"+diachi+"%'";
            }
            

            UpdateTable.LoadData(sql, tbTKNV);
        }
    }//GEN-LAST:event_btTKNVActionPerformed

    private void txtTKTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKTCActionPerformed

    private void btTKMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKMTActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM BangMuonTra WHERE ";
        int kiemtra = 0;
        String manhanvien = this.txtTKMMT.getText();
        String tennhanvien = this.btTKMDG.getText();
        String ngaysinh = this.txtTKMaNV.getText();
        String gioitinh = this.txtTKNM.getText();
        String email = this.txtTKNHT.getText();
        String sdt = this.txtTKTC.getText();
       
        
        if (manhanvien.length() == 0 && tennhanvien.length() == 0 && ngaysinh.length() == 0
            && gioitinh.length() == 0 && email.length() == 0 && sdt.length() == 0 )

        JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin tìm kiếm!", "Thông báo", 1);
        else
        {
            if (manhanvien.length() > 0)
            {
                sql = sql + "MaMuonTra LIKE '%"+manhanvien+"%'";
                kiemtra = 1;
            }
            if (tennhanvien.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "MaDocGia LIKE '%"+tennhanvien+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND MaDocGia LIKE '%"+tennhanvien+"%'";
            }
            if (ngaysinh.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "MaNhanVien LIKE '%"+ngaysinh+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND MaNhanVien LIKE '%"+ngaysinh+"%'";
            }
            if (gioitinh.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "NgayMuon LIKE '%"+gioitinh+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND NgayMuon LIKE '%"+gioitinh+"%'";
            }

            if (email.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "NgayHenTra LIKE '%"+email+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND NgayHenTra LIKE '%"+email+"%'";
            }
            if (sdt.length() > 0)
            {
                if (kiemtra == 0)
                {
                    sql = sql + "TienCoc LIKE '%"+sdt+"%'";
                    kiemtra = 1;
                }
                else
                sql = sql + " AND TienCoc LIKE '%"+sdt+"%'";
            }
            
            UpdateTable.LoadData(sql, tbTKMT);
        }
        
        
    }//GEN-LAST:event_btTKMTActionPerformed

    private void btnewMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewMTActionPerformed
        // TODO add your handling code here:
        this.txtTKMMT.setText(null);
        this.btTKMDG.setText(null);
        this.txtTKMaNV.setText(null);
        this.txtTKNM.setText(null);
        this.txtTKNHT.setText(null);
        this.txtTKTC.setText(null);
    }//GEN-LAST:event_btnewMTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btNewTKNV;
    private javax.swing.JButton btNewTKS;
    private javax.swing.JTextField btTKMDG;
    private javax.swing.JButton btTKMT;
    private javax.swing.JButton btTKNV;
    private javax.swing.JButton btTKS;
    private javax.swing.JButton btnewMT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbTKMT;
    private javax.swing.JTable tbTKNV;
    private javax.swing.JTable tbTKS;
    private javax.swing.JTextField txtDG;
    private javax.swing.JTextField txtMS;
    private javax.swing.JTextField txtNB;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTG;
    private javax.swing.JTextField txtTKDCNV;
    private javax.swing.JTextField txtTKEMNV;
    private javax.swing.JTextField txtTKGTNV;
    private javax.swing.JTextField txtTKMMT;
    private javax.swing.JTextField txtTKMNV;
    private javax.swing.JTextField txtTKMaNV;
    private javax.swing.JTextField txtTKNHT;
    private javax.swing.JTextField txtTKNM;
    private javax.swing.JTextField txtTKNSNV;
    private javax.swing.JTextField txtTKSDTNV;
    private javax.swing.JTextField txtTKTC;
    private javax.swing.JTextField txtTKTNV;
    private javax.swing.JTextField txtTL;
    private javax.swing.JTextField txtTS;
    // End of variables declaration//GEN-END:variables
}
